"""
patch_cricket_gender.py

One-off fix: the 60 draft JSONs generated by batch_generate_cricket_players.py
were missing coreInfo.gender. This script backfills it based on the same
MEN/WOMEN name lists used during generation, matched by playerId.

Usage:
    python patch_cricket_gender.py --dir llm_cricketplayers_drafts

It edits files in place (writes gender into coreInfo) and prints a summary
of any playerId it couldn't confidently classify (so you can fix those by hand).
"""

import argparse
import json
from pathlib import Path

# Keep these in sync with the MEN/WOMEN lists in batch_generate_cricket_players.py.
# Only the slug/playerId form matters here (must match the "playerId" key in the JSON).
MEN_PLAYER_IDS = {
    "ravi_bishnoi",
    "jasprit_bumrah",
    "ishan_kishan",
    "washington_sundar",
    "tilak_varma",
    "sanju_samson",
    "nitish_kumar_reddy",
    "axar_patel",
    "harshit_rana",
    "abhishek_sharma",
    "arshdeep_singh",
    "shivam_dube",
    "shreyas_iyer",
    "varun_chakaravarthy",
    "vaibhav_suryavanshi",
    # add remaining men's squad slugs here if any are missing
}

WOMEN_PLAYER_IDS = {
    "shafali_verma",
    "smriti_mandhana",
    "harmanpreet_kaur",
    "richa_ghosh",
    "deepti_sharma",
    "renuka_singh_thakur",
    "kranti_goud",
    "kamalini_g",
    "sree_charani",
    "nandani_sharma",
    "radha_yadav",
    "arundhati_reddy",
    "shreyanka_patil",
    "pratika_rawal",
    "bharti_fulmali",
    # add remaining women's squad slugs here if any are missing
}


def classify(player_id: str) -> str | None:
    if player_id in MEN_PLAYER_IDS:
        return "Men"
    if player_id in WOMEN_PLAYER_IDS:
        return "Women"
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default="llm_cricketplayers_drafts", help="Folder containing the draft JSON files")
    ap.add_argument("--dry-run", action="store_true", help="Report what would change without writing files")
    args = ap.parse_args()

    folder = Path(args.dir)
    if not folder.exists():
        print(f"Folder not found: {folder.resolve()}")
        return

    files = sorted(folder.glob("*.json"))
    if not files:
        print(f"No .json files found in {folder.resolve()}")
        return

    patched, skipped, unresolved = [], [], []

    for fp in files:
        raw_bytes = fp.read_bytes()
        text = None
        for enc in ("utf-8", "cp1252", "latin-1"):
            try:
                text = raw_bytes.decode(enc)
                break
            except UnicodeDecodeError:
                continue
        if text is None:
            print(f"  ! Could not decode {fp.name} with utf-8/cp1252/latin-1")
            continue

        try:
            data = json.loads(text)
        except Exception as e:
            print(f"  ! Could not parse {fp.name}: {e}")
            continue

        player_id = data.get("playerId") or data.get("coreInfo", {}).get("playerId")
        if not player_id:
            unresolved.append(fp.name)
            continue

        gender = classify(player_id)
        if gender is None:
            unresolved.append(f"{fp.name} (playerId={player_id})")
            continue

        core_info = data.setdefault("coreInfo", {})
        was_non_utf8 = raw_bytes != text.encode("utf-8")
        gender_changed = core_info.get("gender") != gender

        if not gender_changed and not was_non_utf8:
            skipped.append(fp.name)
            continue

        core_info["gender"] = gender

        if not args.dry_run:
            fp.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")

        note = f"{fp.name} -> {gender}"
        if was_non_utf8:
            note += " (re-saved as utf-8)"
        patched.append(note)

    print(f"\nPatched: {len(patched)}")
    for line in patched:
        print(f"  + {line}")

    print(f"\nAlready had correct gender (skipped): {len(skipped)}")

    if unresolved:
        print(f"\nCould not classify ({len(unresolved)}) — check playerId spelling or add to the lists above:")
        for line in unresolved:
            print(f"  ? {line}")

    if args.dry_run:
        print("\n(dry run — no files were modified)")


if __name__ == "__main__":
    main()